#!/bin/bash
## gather mac addresses for a given range
for i in 54 62 34 37 59 33 32 58 57 31 60 221 212 216 113 ; do ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o PasswordAuthentication=no root@192.168.18.$i 'ifconfig | grep ether' ; done | awk '{print $2}' > 18_6_etaj_macs
