#!/bin/bash
#Author
#DATE
#Purpose - Illustrate how to abstract daily log entries
mydate=`date +%b\ %d`
myscript=`basename $0`
myscripterrors=`basename $0`.errors
log1=/var/log/messages
log2=/var/log/maillog
log3=/var/log/secure 
log4=/var/log/cron

for i in $log{1..5}
do
	if [ -e $i ] && [ -s $i ]
	then
		echo $i "Begin"
		sudo grep -E "$mydate" $i 2>$myscripterrors
		echo $i "End"
		echo
	fi
done
# Cleanup STDERR file generated by GREP
if [ -e $myscripterrors ] && [ ! -s $myscripterrors ]
then
rm -f $myscripterrors
fi

#end

